# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-green" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "89f7e743f9e5ecaf1843d892f2c9f22595c9c6a25690cb8402bf2d767d0c7741"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
    on_intel do
      sha256 "0b2e5cba6327b1a8a4360448942f1dc623130868583d6b0b81fb35224c948e24"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
  end
  on_linux do
    on_arm do
      sha256 "1de5cf8e7d8cc430ffc35a73298da65bc655d65d1fe5f56b6aec30107cc50b18"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
    on_intel do
      sha256 "f340aec4f7cbd8c9cb4eaa7b02ddb5658098be58bb14f59af1be66d739977092"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
  end

  name "aws-green"
  desc "Terminal dashboard for live AWS resource health (CodePipeline, CloudFormation, ECS)"
  homepage "https://github.com/ericdahl-dev/aws-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-green"]
    end
  end

  # No zap stanza required
end
