# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-green" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "5be117e22b6ba27eb22667cdd42e4b5a13d670d43bb0c87323b7cdafb9cb275c"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
    on_intel do
      sha256 "d57fb94097d41081e75cfa16b0dfabd7c4197113207dad40c18e15ff84f28bff"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
  end
  on_linux do
    on_arm do
      sha256 "d50b5b2766c17235c43c5d992f21541d441736ba908385c3bfab5487304ace41"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
    on_intel do
      sha256 "2feb92b7122dd2def2c27f26d74ffc9f83c78f02ac09beb45558cebd15664a58"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
  end

  name "aws-green"
  desc "Terminal dashboard for live AWS resource health (CodePipeline, CloudFormation, ECS)"
  homepage "https://github.com/ericdahl-dev/aws-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-green"]
    end
  end

  # No zap stanza required
end
