# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-green" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "490b5737b43b7f6b6e0e1a96efe7e5e77f24a32f1d66cbf663e1b896e39d0528"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
    on_intel do
      sha256 "6e979913623d91b5cfe74e82e0ff5e079412690d4a52290791873d81765b5980"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
  end
  on_linux do
    on_arm do
      sha256 "0b7b87885aa660382ae548ffaeb84295e685b983ca559d673ad1798520254121"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
    on_intel do
      sha256 "f1569b2d2cd6323c14ac3319d840e3078a023fd6aa3cebcb0427a7b694062777"
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v#{version}/aws-green_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ericdahl-dev/aws-green/"
    end
  end

  name "aws-green"
  desc "Terminal dashboard for live AWS resource health (CodePipeline, CloudFormation, ECS)"
  homepage "https://github.com/ericdahl-dev/aws-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-green"]
    end
  end

  # No zap stanza required
end
