# This file was generated by GoReleaser. DO NOT EDIT.
cask "coolify-green" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "636d76fcf3c85601415d6749aaf531953466257d5906ce5eb98dcd55209457e7"
      url "https://github.com/ericdahl-dev/coolify-green/releases/download/v#{version}/coolify-green_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ericdahl-dev/coolify-green/"
    end
    on_intel do
      sha256 "08d08096932fbdc70ee668396e0fb865a74c6fe41dbf89e46e59af5d8a23868a"
      url "https://github.com/ericdahl-dev/coolify-green/releases/download/v#{version}/coolify-green_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ericdahl-dev/coolify-green/"
    end
  end
  on_linux do
    on_arm do
      sha256 "d4ac0d1744f95b5e897435b1e7fbe4fcfc50339887eb8117f1db1ea79920da99"
      url "https://github.com/ericdahl-dev/coolify-green/releases/download/v#{version}/coolify-green_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ericdahl-dev/coolify-green/"
    end
    on_intel do
      sha256 "6e6c802bc223e1ac9418ba6ffd5a8d481c48b8458adbf7300566c5cd7122e82d"
      url "https://github.com/ericdahl-dev/coolify-green/releases/download/v#{version}/coolify-green_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ericdahl-dev/coolify-green/"
    end
  end

  name "coolify-green"
  desc "Terminal dashboard for live Coolify deploy and resource health"
  homepage "https://github.com/ericdahl-dev/coolify-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coolify-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coolify-green"]
    end
  end

  # No zap stanza required
end
