# This file was generated by GoReleaser. DO NOT EDIT.
cask "coolify-green" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "10c00a91f5eb3a230f14f813d88f421a5e75deba893a22be73b58ab73b152d67"
      url "https://github.com/ericdahl-dev/coolify-green/releases/download/v#{version}/coolify-green_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "46295427fc053c89e7a9e58df6719b38dfd0f110969854bc245a8b07a02ef5ab"
      url "https://github.com/ericdahl-dev/coolify-green/releases/download/v#{version}/coolify-green_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8933816293e2a7b8da68bda1c58d52ed8b4bdca92be70e87fffd0f48a44b6c1b"
      url "https://github.com/ericdahl-dev/coolify-green/releases/download/v#{version}/coolify-green_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8308b53cbf42d1a2df2ee46eabe06434826e38690feec8f232b93c3200e640c5"
      url "https://github.com/ericdahl-dev/coolify-green/releases/download/v#{version}/coolify-green_#{version}_linux_amd64.tar.gz"
    end
  end

  name "coolify-green"
  desc "Terminal dashboard for live Coolify deploy and resource health"
  homepage "https://github.com/ericdahl-dev/coolify-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coolify-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coolify-green"]
    end
  end

  # No zap stanza required
end
