# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-green" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "c72d16384c36e15e59b0a5989c55b072aa7c5567a531a028ecbbd714a5a7715e"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "37eb2946ac27c10f9fb50d637684eb7e4a11e5e84fc879ac4bc65870701d397e"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d4d0d85c5259bfab5705df3186c5277829db3e1d996201ce1d496cf5e4b5ffbe"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0547bed4fccd07c1d185db68115033d16292c279abb4de12bf62b4cd7353fb1"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_linux_amd64.tar.gz"
    end
  end

  name "git-green"
  desc "Terminal dashboard for GitHub Actions CI status"
  homepage "https://github.com/ericdahl-dev/git-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-green"]
    end
  end

  # No zap stanza required
end
