# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-green" do
  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "28b3b7a985ba6894432828010c25f7f22f58e9e351e307b75d7e40fed73dfabb"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ec95ca25e54b8ef86b6e30388680899e1612793ccae9f4776029b1e96f7bd01"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1524a901a404af257607e51d122a88bcd547d892a696b4d722a6fca223c67fd3"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0af9c8fa4705da3a48ff84473a4e9d4dddf57ee280cce2de4043408661561c3"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_linux_amd64.tar.gz"
    end
  end

  name "git-green"
  desc "Terminal dashboard for GitHub Actions CI status"
  homepage "https://github.com/ericdahl-dev/git-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-green"]
    end
  end

  # No zap stanza required
end
