# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-green" do
  version "0.7.3"

  on_macos do
    on_arm do
      sha256 "af6be8757a1c31f1c89910ff95db0861fc0ddc05cfa4e28aa81be8dbaae176c2"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1822ee6b3df82e1f8d8d75972f4683556d5bc9e9a2cbcd02de2018a13368fcc7"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "22d7d50c322ebcf036a6c0058fb37b602992bd1dc6667e4a8d527d6bfb39aa06"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5e652ed3c70095131880523feef27122683956ac0dc4fe8128c433a3438f82d"
      url "https://github.com/ericdahl-dev/git-green/releases/download/v#{version}/git-green_#{version}_linux_amd64.tar.gz"
    end
  end

  name "git-green"
  desc "Terminal dashboard for GitHub Actions CI status"
  homepage "https://github.com/ericdahl-dev/git-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-green"]
    end
  end

  # No zap stanza required
end
