# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-green" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "901458925960b8bac42d39b16e935086d6299280dfa6ec3ed4cf97ed8140dfbe"
      url "https://github.com/ericdahl-dev/jira-green/releases/download/v#{version}/jira-green_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f23817ca8ca5f4fed146c71c73ce184677232b1594e6f74485a4094f4a13a707"
      url "https://github.com/ericdahl-dev/jira-green/releases/download/v#{version}/jira-green_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb05a384603bae7bcd37933c4eb67ee54f1400cb71a8f0913b7380841933d1a5"
      url "https://github.com/ericdahl-dev/jira-green/releases/download/v#{version}/jira-green_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "327af1761f0ea9038553b68f1e8a933ede255ffffaab310dbe0b5c71da206934"
      url "https://github.com/ericdahl-dev/jira-green/releases/download/v#{version}/jira-green_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jira-green"
  desc "Terminal dashboard for Jira ticket flow health"
  homepage "https://github.com/ericdahl-dev/jira-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-green"]
    end
  end

  # No zap stanza required
end
