# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-green" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "3249e139422e50bc2f2e15c5f16016f8e026136f2d878b03c9e39f9a537295f4"
      url "https://github.com/ericdahl-dev/jira-green/releases/download/v#{version}/jira-green_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "12dac65efe767ee67e3d2eb6457d30254d69aeb5fc9d37903ecdca950bb2e16b"
      url "https://github.com/ericdahl-dev/jira-green/releases/download/v#{version}/jira-green_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5e6f927f0e8dd098267bd25c55bd29bdf9ca1422eb3ab8d05de52af5a35c7f7e"
      url "https://github.com/ericdahl-dev/jira-green/releases/download/v#{version}/jira-green_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b03fa54f5b17d7b62efade70977df51077da07736fbc3602cb66e352c6247afb"
      url "https://github.com/ericdahl-dev/jira-green/releases/download/v#{version}/jira-green_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jira-green"
  desc "Terminal dashboard for Jira ticket flow health"
  homepage "https://github.com/ericdahl-dev/jira-green"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-green"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-green"]
    end
  end

  # No zap stanza required
end
