# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsGreen < Formula
  desc "Terminal dashboard for live AWS resource health (CodePipeline, CloudFormation, ECS)"
  homepage "https://github.com/ericdahl-dev/aws-green"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v0.3.1/aws-green_0.3.1_darwin_amd64.tar.gz"
      sha256 "6dd5104d54ee49f0150203f7d8c7bab1787e89f520712095cd5136d9e341159c"

      define_method(:install) do
        bin.install "aws-green"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v0.3.1/aws-green_0.3.1_darwin_arm64.tar.gz"
      sha256 "80534c75ee10675b5a13c6c875ae1d3cf9b46b2cf55115a7586adbfea03929d8"

      define_method(:install) do
        bin.install "aws-green"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v0.3.1/aws-green_0.3.1_linux_amd64.tar.gz"
      sha256 "583b0035d88c239605f1542a73237b9329a82884cb4c8b144a1c240acbc5ac5f"
      define_method(:install) do
        bin.install "aws-green"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v0.3.1/aws-green_0.3.1_linux_arm64.tar.gz"
      sha256 "243f61d1430d1c2b5ffc4476005388f3afc189c715cb421bd644158b5ea471bb"
      define_method(:install) do
        bin.install "aws-green"
      end
    end
  end

  test do
    system "#{bin}/aws-green", "--help"
  end
end
