# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsGreen < Formula
  desc "Terminal dashboard for live AWS resource health (CodePipeline, CloudFormation, ECS)"
  homepage "https://github.com/ericdahl-dev/aws-green"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v0.1.0/aws-green_0.1.0_darwin_amd64.tar.gz"
      sha256 "a039f66566664673f6df903b17be0a5a577ea5bf8d45ade7e508e8f4678212d7"

      define_method(:install) do
        bin.install "aws-green"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v0.1.0/aws-green_0.1.0_darwin_arm64.tar.gz"
      sha256 "5e1823a4d739d2dabde0a7f77e527bb62566ac6d52f52d95fd605a95a31fc847"

      define_method(:install) do
        bin.install "aws-green"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v0.1.0/aws-green_0.1.0_linux_amd64.tar.gz"
      sha256 "a9bb8778c617ea77e96cfd3c82174a89a931ee754e3e0376cf0e8b8d815ff9df"
      define_method(:install) do
        bin.install "aws-green"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/aws-green/releases/download/v0.1.0/aws-green_0.1.0_linux_arm64.tar.gz"
      sha256 "898ed8c40dda8339321caf2974e1313909a19ad99e72a925acedbf79c86de971"
      define_method(:install) do
        bin.install "aws-green"
      end
    end
  end

  test do
    system "#{bin}/aws-green", "--help"
  end
end
