# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitGreen < Formula
  desc "Terminal dashboard for GitHub Actions CI status"
  homepage "https://github.com/ericdahl-dev/git-green"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.1/git-green_0.1.1_darwin_amd64.tar.gz"
      sha256 "3136cf66405d67f4db5f76244fc586db77cccb9173b24aa2a508ee782674403e"

      define_method(:install) do
        bin.install "git-green"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.1/git-green_0.1.1_darwin_arm64.tar.gz"
      sha256 "d848e0e5e98210c77b02ee5baac4e793644d76501fb16e8081c0caeb5c7c78af"

      define_method(:install) do
        bin.install "git-green"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.1/git-green_0.1.1_linux_amd64.tar.gz"
      sha256 "2ac4fdbbaecbdaa59c7f23847878e28af5ed445fe459f011209aaac367d0e8e4"
      define_method(:install) do
        bin.install "git-green"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.1/git-green_0.1.1_linux_arm64.tar.gz"
      sha256 "f9f80a66c6ecc3b1ce01513e847e02d92b6475c44c51ccbeb063e6c4075ebe84"
      define_method(:install) do
        bin.install "git-green"
      end
    end
  end

  test do
    system "#{bin}/git-green", "--help"
  end
end
