# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitGreen < Formula
  desc "Terminal dashboard for GitHub Actions CI status"
  homepage "https://github.com/ericdahl-dev/git-green"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.0/git-green_0.1.0_darwin_amd64.tar.gz"
      sha256 "36d5dc98ebcd5e31bf5b4c3346a507799254225fd737e77bdccf885fca4df87a"

      define_method(:install) do
        bin.install "git-green"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.0/git-green_0.1.0_darwin_arm64.tar.gz"
      sha256 "b2c7a32db70da815d53ba8f9fa6d9530b422ceb3215bb91c2f1f82dbf1270eab"

      define_method(:install) do
        bin.install "git-green"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.0/git-green_0.1.0_linux_amd64.tar.gz"
      sha256 "f543f53cef5178786a6ab035237490af1a9afd03238f6c4964e0547efc15b26c"
      define_method(:install) do
        bin.install "git-green"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.0/git-green_0.1.0_linux_arm64.tar.gz"
      sha256 "05c07811afa8f9390e92e70ab8e059335325ebbfed09acb4ee884ad8323f1987"
      define_method(:install) do
        bin.install "git-green"
      end
    end
  end

  test do
    system "#{bin}/git-green", "--help"
  end
end
