# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitGreen < Formula
  desc "Terminal dashboard for GitHub Actions CI status"
  homepage "https://github.com/ericdahl-dev/git-green"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.3/git-green_0.1.3_darwin_amd64.tar.gz"
      sha256 "a49fbfecc46041ab61bc4a22631ff350581cea2b09e1ebc0bb5853defec79f8b"

      define_method(:install) do
        bin.install "git-green"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.3/git-green_0.1.3_darwin_arm64.tar.gz"
      sha256 "f12faafbcd701df68ae7f6e8c3a4c8ee342f8a8661d096d08c9d2f0004a18568"

      define_method(:install) do
        bin.install "git-green"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.3/git-green_0.1.3_linux_amd64.tar.gz"
      sha256 "a084b41a0e1e0ac424ffffdc755aaa9c23091dba79d1958e0ca01f60d5ac0210"
      define_method(:install) do
        bin.install "git-green"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/git-green/releases/download/v0.1.3/git-green_0.1.3_linux_arm64.tar.gz"
      sha256 "97c88ede9d780e3ef99441d4187bbfa2ab44dad5fdf7bc280ad863e9730838a6"
      define_method(:install) do
        bin.install "git-green"
      end
    end
  end

  test do
    system "#{bin}/git-green", "--help"
  end
end
