# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outpost404 < Formula
  desc "Terminal base builder on a remote survival colony"
  homepage "https://github.com/ericdahl-dev/outpost-404"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ericdahl-dev/outpost-404/releases/download/v0.2.0/outpost-404_0.2.0_darwin_amd64.tar.gz"
      sha256 "541fcfd44b13696a77aeb143d2bcf7b878b052d9fb2ea0cd9c0321f75bf6251c"

      define_method(:install) do
        bin.install "outpost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ericdahl-dev/outpost-404/releases/download/v0.2.0/outpost-404_0.2.0_darwin_arm64.tar.gz"
      sha256 "a212ac412f518c442a11f34a29df54c2a2c342527f861fc1243498af7c830fc3"

      define_method(:install) do
        bin.install "outpost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/outpost-404/releases/download/v0.2.0/outpost-404_0.2.0_linux_amd64.tar.gz"
      sha256 "a096175fe271d808bd0a4d355949a3b3f8b73c9c1c220d7a925e81e2b0d5d4a1"
      define_method(:install) do
        bin.install "outpost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/outpost-404/releases/download/v0.2.0/outpost-404_0.2.0_linux_arm64.tar.gz"
      sha256 "272353f27eaa8697da7e824d0a827200f80d4e713cc7f0604ef2ed935e07f629"
      define_method(:install) do
        bin.install "outpost"
      end
    end
  end

  test do
    system "#{bin}/outpost", "-version"
  end
end
