# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outpost404 < Formula
  desc "Terminal base builder on a remote survival colony"
  homepage "https://github.com/ericdahl-dev/outpost-404"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ericdahl-dev/outpost-404/releases/download/v0.1.0/outpost-404_0.1.0_darwin_amd64.tar.gz"
      sha256 "29823b06bb151b87a4dbea0321d50d51b0d5a75e7900ed838114a691a89d0bd2"

      define_method(:install) do
        bin.install "outpost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ericdahl-dev/outpost-404/releases/download/v0.1.0/outpost-404_0.1.0_darwin_arm64.tar.gz"
      sha256 "5ff994a468f3a5d65cc44013a972a20ea5827c3d15bad6b646c286aabfa315b7"

      define_method(:install) do
        bin.install "outpost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/outpost-404/releases/download/v0.1.0/outpost-404_0.1.0_linux_amd64.tar.gz"
      sha256 "47afc4288c6024950e28b03570ebdc8718509142ab0d518eb1d37f6d70702ee1"
      define_method(:install) do
        bin.install "outpost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/outpost-404/releases/download/v0.1.0/outpost-404_0.1.0_linux_arm64.tar.gz"
      sha256 "8de3e3d5a8fa83b298845d32621fdc8e32ba0eb70f4d547d140d262eb3def2c3"
      define_method(:install) do
        bin.install "outpost"
      end
    end
  end

  test do
    system "#{bin}/outpost", "-version"
  end
end
