# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoCleanupTui < Formula
  desc "TUI to find reclaimable node_modules in local git repos"
  homepage "https://github.com/ericdahl-dev/repo-cleanup-tui"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ericdahl-dev/repo-cleanup-tui/releases/download/v0.1.2/repo-cleanup-tui_0.1.2_darwin_amd64.tar.gz"
      sha256 "58353de1edfd69cb4bcb85f870181c67a912c5df0511cbc55bdec70dd0866fd3"

      define_method(:install) do
        bin.install "repo-cleanup-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ericdahl-dev/repo-cleanup-tui/releases/download/v0.1.2/repo-cleanup-tui_0.1.2_darwin_arm64.tar.gz"
      sha256 "c12f288a97230e9e5be585cad2e12980a3a1128398bf67e0db79817bb3a4a23c"

      define_method(:install) do
        bin.install "repo-cleanup-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/repo-cleanup-tui/releases/download/v0.1.2/repo-cleanup-tui_0.1.2_linux_amd64.tar.gz"
      sha256 "5fce2a1487aaea73515796a50f0b0ec4193f0567b409e7b082c2954469441464"
      define_method(:install) do
        bin.install "repo-cleanup-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericdahl-dev/repo-cleanup-tui/releases/download/v0.1.2/repo-cleanup-tui_0.1.2_linux_arm64.tar.gz"
      sha256 "9e63882c27f51ebf162b3105a9bcbe4ccb18a061feada577cb03dc72286e615e"
      define_method(:install) do
        bin.install "repo-cleanup-tui"
      end
    end
  end

  test do
    system "#{bin}/repo-cleanup-tui", "--help"
  end
end
